name: RCOS Blog
description: Blogging about RCOS
meta_description: "Rensselaer Center for Open Source blog."

aboutPage: true

markdown: kramdown
highlighter: rouge

plugins: [jekyll-paginate]
paginate: 10
domain_name: 'http://blog.rcos.io'
google_analytics: 'UA-XXXXXXXX-X'
disqus: false
disqus_shortname: 'your-disqus-shortname'

# Details for the RSS feed generator
url:            'http://blog.rcos.io'
author:         'RCOS Developers and Coordinators'
authorTwitter:  'rcosrpi'

permalink:       /:year/:title/

defaults:
    -
        scope:
            path: "" # empty string for all files
            type: pages
        values:
            layout: default
    -
        scope:
            path: "" # empty string for all files
            type: posts
        values:
            layout: post
    -
        scope:
            path: ""
            type: drafts
        values:
            layout: post
